[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ionwizard"
description = "Installation tools for Ionworks software"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"
license = {text = "BSD 3-Clause License"}
version = "0.0.0"
dependencies = [
    "pyyaml"
]

[project.scripts]
ionwizard-library = "ionwizard.library_wizard:run"
ionwizard-container = "ionwizard.container_wizard:run"

[tool.setuptools_scm]

[tool.setuptools.packages.find]
include = ["ionwizard"]
